"""Asset lists for trading analysis - EXACTLY matching QX Broker available assets."""

# Crypto assets (EXACT names as shown in QX Broker)
CRYPTO_ASSETS = [
    "Cosmos (OTC)",
    "Avalanche (OTC)",
    "Axie Infinity (OTC)",
    "Bitcoin Cash (OTC)",
    "Binance Coin (OTC)",
    "Ripple (OTC)",
    "Bitcoin (OTC)",
    "Polkadot (OTC)",
    "Ethereum Classic (OTC)",
    "Litecoin (OTC)",
    "Trump (OTC)",
    "Solana (OTC)",
    "Dash (OTC)",
    "Ethereum (OTC)",
    "Zcash (OTC)",
    "Chainlink (OTC)",
]

# Forex pairs (EXACT names as shown in QX Broker)
FOREX_ASSETS = [
    "USD/ZAR (OTC)",
    "USD/INR (OTC)",
    "USD/MXN (OTC)",
    "USD/BRL (OTC)",
    "USD/EGP (OTC)",
    "NZD/CHF (OTC)",
    "USD/PKR (OTC)",
    "USD/IDR (OTC)",
    "USD/DZD (OTC)",
    "USD/BDT (OTC)",
    "USD/JPY",
    "USD/NGN (OTC)",
    "NZD/JPY (OTC)",
    "EUR/JPY",
    "EUR/USD",
    "NZD/USD (OTC)",
    "AUD/NZD (OTC)",
    "EUR/GBP",
    "GBP/USD",
    "CAD/CHF (OTC)",
    "NZD/CAD (OTC)",
    "USD/COP (OTC)",
    "USD/PHP (OTC)",
    "EUR/NZD (OTC)",
    "AUD/JPY",
    "CAD/JPY",
    "EUR/CAD",
    "GBP/CAD",
    "AUD/CHF",
    "AUD/USD",
    "USD/CHF",
    "CHF/JPY",
    "AUD/CAD",
    "GBP/JPY",
    "USD/CAD",
    "EUR/AUD",
    "EUR/CHF",
    "GBP/CHF",
    "GBP/AUD",
]

# Commodities (EXACT names as shown in QX Broker)
COMMODITIES_ASSETS = [
    "UKBrent (OTC)",
    "USCrude (OTC)",
    "Silver",
    "Gold",
]

# Stocks (EXACT names as shown in QX Broker)
STOCKS_ASSETS = [
    "Boeing Company (OTC)",
    "Intel (OTC)",
    "Johnson & Johnson (OTC)",
    "Microsoft (OTC)",
    "Pfizer Inc (OTC)",
    "FACEBOOK INC (OTC)",
    "American Express (OTC)",
    "McDonald's (OTC)",
]

# Indices (EXACT names as shown in QX Broker)
INDICES_ASSETS = [
    "CAC 40",
    "EURO STOXX 50",
    "S&P/ASX 200",
    "FTSE 100",
    "IBEX 35",
    "Nikkei 225",
    "FTSE China A50 Index",
    "Hong Kong 50",
]

# Combined asset list for AI Best Trade Finder
ALL_ASSETS = {
    "crypto": CRYPTO_ASSETS,
    "forex": FOREX_ASSETS,
    "indices": INDICES_ASSETS,
    "commodities": COMMODITIES_ASSETS,
    "stocks": STOCKS_ASSETS,
}

# Display names for categories
CATEGORY_NAMES = {
    "crypto": "🪙 Crypto",
    "forex": "💱 Forex",
    "indices": "📈 Indices",
    "commodities": "🏆 Commodities",
    "stocks": "📊 Stocks",
}

# Asset display name mapping (symbol -> friendly name) - Now assets ARE the friendly names
ASSET_NAMES = {
    # Crypto - names are already friendly
    "Cosmos (OTC)": "Cosmos",
    "Avalanche (OTC)": "Avalanche",
    "Axie Infinity (OTC)": "Axie Infinity",
    "Bitcoin Cash (OTC)": "Bitcoin Cash",
    "Binance Coin (OTC)": "Binance Coin",
    "Ripple (OTC)": "Ripple",
    "Bitcoin (OTC)": "Bitcoin",
    "Polkadot (OTC)": "Polkadot",
    "Ethereum Classic (OTC)": "Ethereum Classic",
    "Litecoin (OTC)": "Litecoin",
    "Trump (OTC)": "Trump",
    "Solana (OTC)": "Solana",
    "Dash (OTC)": "Dash",
    "Ethereum (OTC)": "Ethereum",
    "Zcash (OTC)": "Zcash",
    "Chainlink (OTC)": "Chainlink",
    # Forex - names are already friendly
    "USD/ZAR (OTC)": "USD/ZAR",
    "USD/INR (OTC)": "USD/INR",
    "USD/MXN (OTC)": "USD/MXN",
    "USD/BRL (OTC)": "USD/BRL",
    "USD/EGP (OTC)": "USD/EGP",
    "NZD/CHF (OTC)": "NZD/CHF",
    "USD/PKR (OTC)": "USD/PKR",
    "USD/IDR (OTC)": "USD/IDR",
    "USD/DZD (OTC)": "USD/DZD",
    "USD/BDT (OTC)": "USD/BDT",
    "USD/JPY": "USD/JPY",
    "USD/NGN (OTC)": "USD/NGN",
    "NZD/JPY (OTC)": "NZD/JPY",
    "EUR/JPY": "EUR/JPY",
    "EUR/USD": "EUR/USD",
    "NZD/USD (OTC)": "NZD/USD",
    "AUD/NZD (OTC)": "AUD/NZD",
    "EUR/GBP": "EUR/GBP",
    "GBP/USD": "GBP/USD",
    "CAD/CHF (OTC)": "CAD/CHF",
    "NZD/CAD (OTC)": "NZD/CAD",
    "USD/COP (OTC)": "USD/COP",
    "USD/PHP (OTC)": "USD/PHP",
    "EUR/NZD (OTC)": "EUR/NZD",
    "AUD/JPY": "AUD/JPY",
    "CAD/JPY": "CAD/JPY",
    "EUR/CAD": "EUR/CAD",
    "GBP/CAD": "GBP/CAD",
    "AUD/CHF": "AUD/CHF",
    "AUD/USD": "AUD/USD",
    "USD/CHF": "USD/CHF",
    "CHF/JPY": "CHF/JPY",
    "AUD/CAD": "AUD/CAD",
    "GBP/JPY": "GBP/JPY",
    "USD/CAD": "USD/CAD",
    "EUR/AUD": "EUR/AUD",
    "EUR/CHF": "EUR/CHF",
    "GBP/CHF": "GBP/CHF",
    "GBP/AUD": "GBP/AUD",
    # Commodities - names are already friendly
    "UKBrent (OTC)": "UKBrent",
    "USCrude (OTC)": "USCrude",
    "Silver": "Silver",
    "Gold": "Gold",
    # Stocks - names are already friendly
    "Boeing Company (OTC)": "Boeing",
    "Intel (OTC)": "Intel",
    "Johnson & Johnson (OTC)": "Johnson & Johnson",
    "Microsoft (OTC)": "Microsoft",
    "Pfizer Inc (OTC)": "Pfizer",
    "FACEBOOK INC (OTC)": "Facebook",
    "American Express (OTC)": "American Express",
    "McDonald's (OTC)": "McDonald's",
    # Indices - names are already friendly
    "CAC 40": "CAC 40",
    "EURO STOXX 50": "EURO STOXX 50",
    "S&P/ASX 200": "S&P/ASX 200",
    "FTSE 100": "FTSE 100",
    "IBEX 35": "IBEX 35",
    "Nikkei 225": "Nikkei 225",
    "FTSE China A50 Index": "FTSE China A50",
    "Hong Kong 50": "Hong Kong 50",
}
